// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTI3zzPeqltuqX6VkCQ48UpEJXf094blE',
    appId: '1:228540623446:web:4b394a838371909164e9f7',
    messagingSenderId: '228540623446',
    projectId: 'fianace-tracker-app',
    authDomain: 'fianace-tracker-app.firebaseapp.com',
    storageBucket: 'fianace-tracker-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI9pCta3hdNE0TURSyM2VfkZ7aaZiipv4',
    appId: '1:228540623446:android:6a011db60442d36164e9f7',
    messagingSenderId: '228540623446',
    projectId: 'fianace-tracker-app',
    storageBucket: 'fianace-tracker-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAog5OVbsUIfPYuZvvGWFve7hj635a6AJw',
    appId: '1:228540623446:ios:ca55d46c1c1b1ed964e9f7',
    messagingSenderId: '228540623446',
    projectId: 'fianace-tracker-app',
    storageBucket: 'fianace-tracker-app.appspot.com',
    iosBundleId: 'com.example.financeTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAog5OVbsUIfPYuZvvGWFve7hj635a6AJw',
    appId: '1:228540623446:ios:ca55d46c1c1b1ed964e9f7',
    messagingSenderId: '228540623446',
    projectId: 'fianace-tracker-app',
    storageBucket: 'fianace-tracker-app.appspot.com',
    iosBundleId: 'com.example.financeTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTI3zzPeqltuqX6VkCQ48UpEJXf094blE',
    appId: '1:228540623446:web:9123bbcc4b33332864e9f7',
    messagingSenderId: '228540623446',
    projectId: 'fianace-tracker-app',
    authDomain: 'fianace-tracker-app.firebaseapp.com',
    storageBucket: 'fianace-tracker-app.appspot.com',
  );
}
